inputs:
  prefix:
    description: 'Install prefix'
    default: '.'

  parallel:
    required: false
    description: 'Thread count'
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Cache AWS sdk build
      id: aws-sdk
      uses: actions/cache@v3
      with:
        path: ${{ inputs.prefix }}
        key: aws

    - name: Download AWS sdk
      if: steps.aws-sdk.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: aws/aws-sdk-cpp
        ref: 1.11.140
        path: ${{ inputs.prefix }}
        submodules: 'recursive'

    - name: Build AWS sdk
      if: steps.aws-sdk.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.prefix }}
      shell: bash
      run: |
        mkdir build -p
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_ONLY="core" -DCUSTOM_MEMORY_MANAGEMENT=OFF
        make -j ${{ inputs.parallel }}

    - name: Install AWS sdk
      working-directory: ${{ inputs.prefix }}/build
      shell: bash
      run: |
        sudo make install