inputs:
  prefix:
    description: 'Install prefix'
    default: '.'

  parallel:
    required: false
    description: 'Thread count'
    default: '1'

runs:
  using: "composite"
  steps:
    - name: Cache AWS lambda runtime build
      id: aws-lambda-runtime
      uses: actions/cache@v3
      with:
        path: ${{ inputs.prefix }}
        key: aws

    - name: Download AWS lambda runtime
      if: steps.aws-lambda-runtime.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: awslabs/aws-lambda-cpp
        ref: v0.2.8
        path: ${{ inputs.prefix }}
        submodules: true

    - name: Build AWS lambda runtime
      if: steps.aws-lambda-runtime.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.prefix }}
      shell: bash
      run: |
        mkdir build -p
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
        make -j ${{ inputs.parallel }}

    - name: Install AWS lambda runtime
      working-directory: ${{ inputs.prefix }}/build
      shell: bash
      run: |
        sudo make install